language: python
python:
    3.5
install:
    - "pip install numpy"
    - "pip install networkx"
    - "pip install matplotlib"
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coveralls"
script: "py.test --cov=./infection.py ./test/"
after_success:
    coveralls
